version: '3.7'
networks: 
  api:
services:
  gateway-api:
    image: node:10.7
    volumes:
      - ./gateway:/gateway
    ports:
      - 3000:3000
    command: bash -c "cd /gateway && npm i && node server"
    networks: 
      - api
    depends_on:
      - cadastro_organizacao_api
      - cadastro_paciente-_pi
  cadastro_organizacao_db:
    image: mongo:3.4
  cadastro_organizacao_api:
    image: node:10.7
    volumes:
      - ./cadastro_organizacao:/cadastro_organizacao
    ports:
      - 3001:3000
    command: bash -c "cd /cadastro_organizacao && npm i && node server"
    networks: 
      - api
  cadastro_paciente_db:
    image: mongo:3.4
  cadastro_paciente_api:
    image: node:10.7
    volumes: 
      - ./cadastro_paciente:/cadastro_paciente
    ports:
      - 3002:3000
    command: bash -c "cd /cadastro_paciente && npm i && node server"
    networks: 
      - api