version: '3.7'
networks: 
  api:
services:
  gateway-api:
    image: node:10.7
    volumes:
      - ./gateway:/gateway
    ports:
      - 3000:3000
    command: bash -c "cd /gateway && npm i && node server"
    networks: 
      - api
    depends_on:
      - cadastro-organizacao-api
      - cadastro-paciente-api
  cadastro-organizacao-db:
    image: mongo:3.4
  cadastro-organizacao-api:
    image: node:10.7
    volumes:
      - ./cadastro-organizacao:/cadastro-organizacao
    ports:
      - 3001:3000
    command: bash -c "cd /cadastro-organizacao && npm i && node server"
    networks: 
      - api
  cadastro-paciente-db:
    image: mongo:3.4
  cadastro-paciente-api:
    image: node:10.7
    volumes: 
      - ./cadastro-paciente:/cadastro-paciente
    ports:
      - 3002:3000
    command: bash -c "cd /cadastro-paciente && npm i && node server"
    networks: 
      - api