version: '3.7'
volumes:
services:
  db_paciente:
    image: mongo:4.0
    volumes:
      - data_db_paciente
  db_organizacao:
    image: mongo:4.0
    volumes:
      - data_db_organizacao
  db_carteira:
    image: mongo:4.0
    volumes:
      - data_db_carteira
  db_prontuario:
    image: mongo:4.0
    volumes:
      - data_db_prontuario

  api_paciente:
    image: node:10.7
    volumes: 
      - ./service_paciente:/service_paciente
    links:
      - db_paciente
    ports:
      - "3000"
    command: bash -c "cd /service_paciente && npm i && node server"

  api_organizacao:
    image: node:10.7
    volumes: 
      - ./service_organizacao:/service_organizacao
    links:
      - db_paciente
    ports:
      - "3000"
    command: bash -c "cd /service_organizacao && npm i && node server"
  
  api_carteira:
    image: node:10.7
    volumes: 
      - ./service_carteira:/service_carteira
    links:
      - db_paciente
    ports:
      - "3000"
    command: bash -c "cd /service_carteira && npm i && node server"

  api_prontuario:
    image: node:10.7
    volumes: 
      - ./service_prontuario:/service_prontuario
    links:
      - db_paciente
    ports:
      - "3000"
    command: bash -c "cd /service_prontuario && npm i && node server"

  api_gateway:
    image: node:10.7
    volumes:
      - ./service_gateway:/service_gateway
    links:
      - api_paciente
      - api_organizacao
      - api_carteira
      - api_prontuario
    ports:
      - "80:3000"
    command: bash -c "cd /service_gateway && npm i && node server"