version: '3.7'
services:
  db_paciente:
    image: mongo:4.0
  db_organizacao:
    image: mongo:4.0
  db_carteira:
    image: mongo:4.0
  db_prontuario:
    image: mongo:4.0

  api_paciente:
    image: mhart/alpine-node:10.15.1
    volumes: 
      - ./service_paciente:/service_paciente
    links:
      - db_paciente
    ports:
      - "3000"
    command: bash -c "cd /service_paciente && npm i && node server"

  api_organizacao:
    image: mhart/alpine-node:10.15.1
    volumes: 
      - ./service_organizacao:/service_organizacao
    links:
      - db_paciente
    ports:
      - "3000"
    command: bash -c "cd /service_organizacao && npm i && node server"
  
  api_carteira:
    image: mhart/alpine-node:10.15.1
    volumes: 
      - ./service_carteira:/service_carteira
    links:
      - db_paciente
    ports:
      - "3000"
    command: bash -c "cd /service_carteira && npm i && node server"

  api_prontuario:
    image: mhart/alpine-node:10.15.1
    volumes: 
      - ./service_prontuario:/service_prontuario
    links:
      - db_paciente
    ports:
      - "3000"
    command: bash -c "cd /service_prontuario && npm i && node server"

  api_gateway:
    build: service_gateway
    volumes:
      - ./service_gateway:/service_gateway
    links:
      - api_paciente
      - api_organizacao
      - api_carteira
      - api_prontuario
    ports:
      - "3000:3000"